apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment

spec:
  template: 
    metadata:
      name: backend-pod 
      labels:
        app: mybackend
        component: backend
        type: backend
    spec: 
      containers:
        - name: backend-container
          image: maciejtokarz/project:Dev-b-0-4
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
          
  replicas: 5
  selector:
    matchLabels:
      type: backend
 