apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment

spec:
  template: 
    metadata:
      name: backend-pod 
      labels:
        app: mybackend
        component: backend
        type: backend
    spec: 
      containers:
        - name: backend-contaier
          image: maciejtokarz/project:Dev-b-0-3
          ports:
            - containerPort: 5000
          env:
          - name: MONGO_HOST
            value: mongobd-clusterip
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_DATABASE
            value: local
          - name: REDIS_HOST
            value: redis-clusterip
          - name: REDIS_PORT
            value: "6379"
          
  replicas: 1
  selector:
    matchLabels:
      type: backend
 