apiVersion: v1
kind: Service
metadata: 
  name: frontend-clusterip
  namespace: development

spec: 
  type: ClusterIP
  ports: 
    - port: 80
      targetPort: 80

  selector: 
    component: frontend