apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment

spec:
  template: 
    metadata:
      name: frontend-pod
      labels:
        app: myfrontend
        component: frontend
        type: frontend
    spec: 
      containers:
        - name: frontend-container
          image: maciejtokarz/project:Dev-f-dev-0-5
          ports:
          - containerPort: 80  
  replicas: 5
  selector:
    matchLabels:
      type: frontend