apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mongodb-prod-pv
  labels:
    type: local

spec: 
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prod/mongodb"
